// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALT2mRl1JDp0CAyLXiAGAYOYaBNXLF-4g',
    appId: '1:603293938333:web:a2d6523941aa0ec8975a74',
    messagingSenderId: '603293938333',
    projectId: 'uni-buddy-fb307',
    authDomain: 'uni-buddy-fb307.firebaseapp.com',
    storageBucket: 'uni-buddy-fb307.firebasestorage.app',
    measurementId: 'G-2ZYS2PZPVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-HGwVnbJnIJk4ySVep65vk_NZ8KYCbR0',
    appId: '1:603293938333:android:41ab78bb7fea29e0975a74',
    messagingSenderId: '603293938333',
    projectId: 'uni-buddy-fb307',
    storageBucket: 'uni-buddy-fb307.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwDLvXJrfGeAplUdc9R4uUVDuLFWzEW84',
    appId: '1:603293938333:ios:5841acf28878e718975a74',
    messagingSenderId: '603293938333',
    projectId: 'uni-buddy-fb307',
    storageBucket: 'uni-buddy-fb307.firebasestorage.app',
    iosClientId: '603293938333-2uca0sgktmvq9c83bnapsi2kfi90us2h.apps.googleusercontent.com',
    iosBundleId: 'com.unibuddy.uniBuddy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwDLvXJrfGeAplUdc9R4uUVDuLFWzEW84',
    appId: '1:603293938333:ios:5841acf28878e718975a74',
    messagingSenderId: '603293938333',
    projectId: 'uni-buddy-fb307',
    storageBucket: 'uni-buddy-fb307.firebasestorage.app',
    iosClientId: '603293938333-2uca0sgktmvq9c83bnapsi2kfi90us2h.apps.googleusercontent.com',
    iosBundleId: 'com.unibuddy.uniBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALT2mRl1JDp0CAyLXiAGAYOYaBNXLF-4g',
    appId: '1:603293938333:web:4c171b5a390a34a9975a74',
    messagingSenderId: '603293938333',
    projectId: 'uni-buddy-fb307',
    authDomain: 'uni-buddy-fb307.firebaseapp.com',
    storageBucket: 'uni-buddy-fb307.firebasestorage.app',
    measurementId: 'G-1Y7V3PBEJS',
  );
}
